name: Build and push docker image #haida lname ana bektbo metl mabade 

on: # hone b2elo listen lal events lirah ekteblak yehon
  push: 
    #branches: [ $main ] 
     #pull_request: 
    # branches: [ $main ] 
          
jobs:      #son but est de faire build and push 
  build-and-push:
    runs-on: ubuntu-latest 

    steps: 
      - name: checkout the repo 
        uses: actions/checkout@v6 

      - name: use node
        uses: actions/setup-node@v6 
        with:
          node-version: 24 #hone eltelo st3ml hay el version specifique de node 
      - name: installer dependences node_module    
        run: npm ci #binazel node_module 
      - name: faire Run test   
        run: npm test #ba3mel run lal test la et2akd eno l app 3am temche sas erreur 






      # - name: login to dockerhub 
      #   uses: docker/login-action@v3  # uses katabtlo url cz hay l url hiye 3ibara 3an workflow jehze bigithub lata3ml action m3ayane 
      #   with:
      #     username: ${{ vars.DOCKERHUB_USERNAME }} # wa2ta fetet3ala el login-action bl github l2it eno v3 hiye lmoteha w 3atene ektob username w password bihayda el chakel
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: build and push docker image to docker hub
      #   env: #env lama ykun bade 3ati envirement variable .env
      #     REPOSITORY: ngnix #hone haida esm el repository li ana 5ala2to 3nde bl github sabato hone huwe w latest lahata lcommande docker build wpush bs elle va creer l'image te5od esma mn hone 
      #     IMAGE_TAG: latest
      #   run: |  #run betsa3mela lama kun bade ektob commande , eza bade ektobe commande wehde bl run bhot el commnade 3a nafes sater el run bas Wa2ta ykun bade ektob aktar mn commande bhot pip 3a sater el run w bnzal 3anl sater
      #     docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG .  
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPOSITORY:$IMAGE_TAG